[package]
name = "omacloud-app"
description = "The Omacloud app (GTK4, libadwaita)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gtk = { package = "gtk4", version = "0.11", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.9", features = ["v1_5"] }
serde_json.workspace = true
